### PR TITLE
support swift-package-manager

### LINKED ISSUE #320: SwiftPM support
Hi,
  [SwiftPM](https://goo.gl/E01ufX) is Swift's official package manager.
  
  Here some articles about SwiftPM:
  
  * [An Introduction to the Swift Package Manager](https://goo.gl/byiOc6)
  * [Swift Dependency Management for iOS](https://goo.gl/7eaz1A)
  * [Getting Started with Swift Package Manager (SwiftPM)](https://goo.gl/rCHeQU)
  * [Swift.org: Package Manager](https://goo.gl/E01ufX)
  
  When your component is compatible with SwiftPM add on your `README.md` [SwiftPM Compatible](https://goo.gl/E01ufX) badge on top and add a section for the installation with SwiftPM.

### PR DESCRIPTION
**Pull request by MarcSteven**
Made the SDK support swift-package-manager.
fix #320

### CODE REVIEW

**Comment by zihejia** [comment]
wow, thanks so much @MarcSteven for this PR, this is huge! I will take a look.

**Comment by MarcSteven** [comment]
@zihejia  Ok， Please review.

**Comment by MarcSteven** [comment]
Is it okay? If have any issues, please let me know. 
@zihejia

**Comment by mman** [comment]
Looking again at the provided Package.swift it actually does nothing. All the sources for mixpanel are currently located in top-level ``Mixpanel`` directory. This should be cleaned up and moved into ``Sources/Mixpanel``. The Package.swift Target should be named ``Mixpanel`` so that you can actually ``import Mixpanel`` from your sources. Definitely requires more work to separate ``.swift`` source files away from ``.xib`` as well as ``.h`` and ``.m`` files.

**Comment by menan** [comment]
This doesn't work.

**Comment by zihejia** [comment]
Hi @MarcSteven, many thanks for your contribution! we have now officially release the SPM support https://github.com/mixpanel/mixpanel-swift/releases/tag/v2.8.0., I'm closing this one now.

**Pull request closed without merging**
